apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-nonprod
spec:
  encryptedData:
    DB_PASSWORD: AgCgbOiDNdSvXKL+yvdOX8KarMfXyLoLckPg+3Uq8iS8E12vIFOUlaKEq6Hc297n+jdk47jtnSSNUIBPOI4c0g/yeE+WE6sgy4Y34Izqw8oW5DdEfjzJljW4Bfm6OxG+wHAGpCndQgPfVzAaSSC5KF64lbz3iz6//byNrrVIMzCE919c8HJJkc4oVi+AyhITPcb3mkZ4k4r3Rcumw4F7MllCRjTZbtJdh0r7GRKmhqDbJQ4WMXuzzjWuP17Q1lFsZHD7MdBZkF4O+nHgtrV0KJfyXII+VjmeIkGaXuvZHzL+Y0HLEjTclH+HOSYs1N6aZu5RksCCQ4y4I/lFer7/oM+1ILB6/H3AgJJEttXmemzfiP5Z0WY94mCQZ6T4/Qjg7eEcT8ROGESTxsFMj4XjOR3kfg9OS4haKf8frUFX7kPHF1vZVm2RsxtVIaYoyOneVqJfsrli+j0Z4s0YssZMVsPiXfxivGsEQU5va8axS/HheN6v0dkp6nU0ERUDN6JhDcH89r39j7rIHBEyp/VWjsfICxrVfCI72iu8QAHnwuzk5mB0xIl+z3CsO5X1scWEFzfjPxa7SfE12C2y7gu6Q0L11+ev19uS7N9uPT+X+nsEsfpB6vCZSAMLB/NUNbl4BgppzwJTWWh7jbPPBKnvZYjuGc93/tmaN5V6LQm8LDOky0Z0RYDNHLLj5N92QOv1EYibc1TxLEyRtg==
    DB_USER: AgAhyzq63OgrwedgTgps5ZEYlt+vOuhv+knuP3YkNQYwooC8VdFU3uySQrtPFN2z9IRsMdI9dAxj7hS3tbLF+Xg2X5KKL2gcYc6I7ERV2MaC72IGmRhw743oKQ9IyD2NEne19Uy7ypows/CVsszJHEHxPyogy9vX5Uviu1xNIJR74q9ZQ3cmEXDxMOX8NAmTWWiITtmhlz1gZk8fIDEZgO0nrsFijPmKHRAOqsoxICfHznIost1zh8EFQvlaG7uom0W5NVl6sqSRGYtocxtSK4elTIHuKXPIufZj6R/8UnjPXvUktDzRAzvt8mNIrUc/kHoxnwwX3G2/YkLpAtzkUZDiktSXF1Z1xjGllw0kmfLYoSBKwaG7AA+udO44CTYIxgx+MJPkZoHl7uubvW0vMi3/VG3ZWnDXjYNn20MsnyJuAP8OQGcJE8Xv473VDM3wXVv5eQFed5I5dwJIs6WVOUUwMr/5Eo6/hZxawJWlMrODvoqwEOjRIQ09LCSxwQHFFeaCG65iIe0eHjDUyl66T1mOjXUTd474XG0cmojzPwzwHbvr3IXzo6F/LKUuu1dTmUxlKaBrxM0qCbH9BH1pDAqzMh7ESJl4TgYdfjujgRlL1r9mGTG0h9hk8PjoBEmNTOYThOHCYzBFNqR++aO/WNkcjJHCLnlpAD/MViy+8FgaaUwj9FUQMOrcLD7dxBuUv11e75FBK29bWw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-nonprod
    type: Opaque

